[package]
name = "bl808-blinky-m0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bl808-pac = "0.0.1"
